name = "corsproxy"
main = "src/index.js"
compatibility_date = "2026-08-17"

[vars]
ALLOWED_HOSTS = "dirkjan.nl,www.dirkjan.nl"

[observability]
enabled = true

[observability.logs]
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.01
