name = "corsproxy"
main = "src/index.js"
compatibility_date = "2026-08-17"

[vars]
ALLOWED_HOSTS = "dirkjan.nl,www.dirkjan.nl,gocomics.com,*.gocomics.com,assets.amuniversal.com,picayune.uclick.com,www.arcamax.com,resources.arcamax.com,garfield.fandom.com,static.wikia.nocookie.net"

[observability]
enabled = true

[observability.logs]
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.01
